---
- name: deploy local repos for centos7
  hosts: centos7:!repo01.buczkowski.local
  tasks:
  - name: create /etc/yum.repos.d/bak if required
    become: yes
    file:
      path: /etc/yum.repos.d/bak
      state: directory
      mode: '0755'
  - name: back up centos repos if required
    become: yes 
    shell:
      cmd: mv /etc/yum.repos.d/CentOS-* /etc/yum.repos.d/bak/
    failed_when: False
    ignore_errors: True
  - name: create local-repos.repo
    become: yes
    copy:
      src: /home/pbucz/local-repos.repo
      dest: /etc/yum.repos.d/local-repos.repo
      owner: root
      group: root
      mode: 0644
