---
- hosts: centos7:!admin01.buczkowski.local:!kube01.buczkowski.local:!minion01.buczkowski.local:!minion02.buczkowski.local
  tasks:
    - name: upgrade all packages and reboot all centos7 hosts except for admin01 and the kubernetes cluster
      become: yes
      yum:
          name: '*'
          state: latest
    - name: reboot
      become: yes
      reboot:
