---
- name: check for updates
  hosts: centos8
  tasks:
    - name: check for updates (yum)  
      become: yes
      yum: list=updates update_cache=yes
      register: yum_output
    - debug: var=yum_output
