---
- hosts: centos7:!admin01.buczkowski.local
  tasks:
    - name: upgrade all packages and reboot all centos7 hosts except for admin01
      become: yes
      yum:
          name: '*'
          state: latest
    - name: reboot
      become: yes
      reboot:
